# config.toml - Hugo configuration file example

baseURL = "https://daan.it.com/"
languageCode = "nl"
title = "Jouw Website"
  # Navigation links
  [[params.navigation]]
    name = 'Weeknotes'
    url = "/weeknotes"
